//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputSystem/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""1a079dc0-0fa8-4eb2-82f8-934193cc6a90"",
            ""actions"": [
                {
                    ""name"": ""MovePlayer1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0e8f4c6d-d912-4ce5-98d7-60848098cbf1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePlayer2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bc332a15-e0df-4b5c-aaa7-dcc2736a291e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootPlayer1Up"",
                    ""type"": ""Button"",
                    ""id"": ""57e7699a-f96f-4eb2-acbb-a13536e1a9b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootPlayer2Up"",
                    ""type"": ""Button"",
                    ""id"": ""c8a2c826-7166-4ce0-9b40-b3d2c379ca45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootPlayer1Down"",
                    ""type"": ""Button"",
                    ""id"": ""65b6d2b8-a8df-4e1b-a41d-79717057429f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootPlayer2Down"",
                    ""type"": ""Button"",
                    ""id"": ""7d52ccbb-a533-4cfb-af49-bb5de3e4d25f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""55045d56-1a03-4928-a613-4bcc4f9b1c38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WS"",
                    ""id"": ""5a07df7d-8714-4c5c-90ad-e6445b7dc5b6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0407a6a1-8c1a-45b0-badb-72edd97a5be9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8df8f5ec-e6c8-45d1-981b-35aac59bca18"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""e38f11d4-fdea-4ef3-bf5d-c7d520c3d383"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f649f953-eb62-4c74-936f-21be5da5d1ef"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ce0130d5-7c27-49b5-8419-a3566ca2e8f2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f91d5b84-8e76-4433-b3df-c71522e7f9d2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootPlayer1Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c556c6cd-d4ba-479b-afd4-b930eaf8dd34"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootPlayer1Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d41a7fa7-3ac9-4567-b91b-df122e7bf2d8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootPlayer2Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""243c5ad6-ab78-4e59-a829-98dca25993c6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootPlayer2Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3664a21-3dac-4c74-a7e4-404bc18e5714"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f59cfd39-c6ed-48cd-abf0-ce7d0a9d64b9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Navigation"",
            ""id"": ""bd2585a7-cff7-4337-b634-04e3a473b0de"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""bb75e1ba-c114-42db-b071-675e0e6225a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8ec8dde-b865-49f3-909b-6216467353da"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_MovePlayer1 = m_Character.FindAction("MovePlayer1", throwIfNotFound: true);
        m_Character_MovePlayer2 = m_Character.FindAction("MovePlayer2", throwIfNotFound: true);
        m_Character_ShootPlayer1Up = m_Character.FindAction("ShootPlayer1Up", throwIfNotFound: true);
        m_Character_ShootPlayer2Up = m_Character.FindAction("ShootPlayer2Up", throwIfNotFound: true);
        m_Character_ShootPlayer1Down = m_Character.FindAction("ShootPlayer1Down", throwIfNotFound: true);
        m_Character_ShootPlayer2Down = m_Character.FindAction("ShootPlayer2Down", throwIfNotFound: true);
        m_Character_PauseMenu = m_Character.FindAction("PauseMenu", throwIfNotFound: true);
        // Navigation
        m_Navigation = asset.FindActionMap("Navigation", throwIfNotFound: true);
        m_Navigation_Newaction = m_Navigation.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private ICharacterActions m_CharacterActionsCallbackInterface;
    private readonly InputAction m_Character_MovePlayer1;
    private readonly InputAction m_Character_MovePlayer2;
    private readonly InputAction m_Character_ShootPlayer1Up;
    private readonly InputAction m_Character_ShootPlayer2Up;
    private readonly InputAction m_Character_ShootPlayer1Down;
    private readonly InputAction m_Character_ShootPlayer2Down;
    private readonly InputAction m_Character_PauseMenu;
    public struct CharacterActions
    {
        private @GameInput m_Wrapper;
        public CharacterActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePlayer1 => m_Wrapper.m_Character_MovePlayer1;
        public InputAction @MovePlayer2 => m_Wrapper.m_Character_MovePlayer2;
        public InputAction @ShootPlayer1Up => m_Wrapper.m_Character_ShootPlayer1Up;
        public InputAction @ShootPlayer2Up => m_Wrapper.m_Character_ShootPlayer2Up;
        public InputAction @ShootPlayer1Down => m_Wrapper.m_Character_ShootPlayer1Down;
        public InputAction @ShootPlayer2Down => m_Wrapper.m_Character_ShootPlayer2Down;
        public InputAction @PauseMenu => m_Wrapper.m_Character_PauseMenu;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterface != null)
            {
                @MovePlayer1.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer1;
                @MovePlayer1.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer1;
                @MovePlayer1.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer1;
                @MovePlayer2.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer2;
                @MovePlayer2.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer2;
                @MovePlayer2.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovePlayer2;
                @ShootPlayer1Up.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Up;
                @ShootPlayer1Up.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Up;
                @ShootPlayer1Up.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Up;
                @ShootPlayer2Up.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Up;
                @ShootPlayer2Up.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Up;
                @ShootPlayer2Up.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Up;
                @ShootPlayer1Down.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Down;
                @ShootPlayer1Down.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Down;
                @ShootPlayer1Down.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer1Down;
                @ShootPlayer2Down.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Down;
                @ShootPlayer2Down.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Down;
                @ShootPlayer2Down.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnShootPlayer2Down;
                @PauseMenu.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseMenu;
            }
            m_Wrapper.m_CharacterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePlayer1.started += instance.OnMovePlayer1;
                @MovePlayer1.performed += instance.OnMovePlayer1;
                @MovePlayer1.canceled += instance.OnMovePlayer1;
                @MovePlayer2.started += instance.OnMovePlayer2;
                @MovePlayer2.performed += instance.OnMovePlayer2;
                @MovePlayer2.canceled += instance.OnMovePlayer2;
                @ShootPlayer1Up.started += instance.OnShootPlayer1Up;
                @ShootPlayer1Up.performed += instance.OnShootPlayer1Up;
                @ShootPlayer1Up.canceled += instance.OnShootPlayer1Up;
                @ShootPlayer2Up.started += instance.OnShootPlayer2Up;
                @ShootPlayer2Up.performed += instance.OnShootPlayer2Up;
                @ShootPlayer2Up.canceled += instance.OnShootPlayer2Up;
                @ShootPlayer1Down.started += instance.OnShootPlayer1Down;
                @ShootPlayer1Down.performed += instance.OnShootPlayer1Down;
                @ShootPlayer1Down.canceled += instance.OnShootPlayer1Down;
                @ShootPlayer2Down.started += instance.OnShootPlayer2Down;
                @ShootPlayer2Down.performed += instance.OnShootPlayer2Down;
                @ShootPlayer2Down.canceled += instance.OnShootPlayer2Down;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
            }
        }
    }
    public CharacterActions @Character => new CharacterActions(this);

    // Navigation
    private readonly InputActionMap m_Navigation;
    private INavigationActions m_NavigationActionsCallbackInterface;
    private readonly InputAction m_Navigation_Newaction;
    public struct NavigationActions
    {
        private @GameInput m_Wrapper;
        public NavigationActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Navigation_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Navigation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavigationActions set) { return set.Get(); }
        public void SetCallbacks(INavigationActions instance)
        {
            if (m_Wrapper.m_NavigationActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_NavigationActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_NavigationActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_NavigationActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_NavigationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public NavigationActions @Navigation => new NavigationActions(this);
    public interface ICharacterActions
    {
        void OnMovePlayer1(InputAction.CallbackContext context);
        void OnMovePlayer2(InputAction.CallbackContext context);
        void OnShootPlayer1Up(InputAction.CallbackContext context);
        void OnShootPlayer2Up(InputAction.CallbackContext context);
        void OnShootPlayer1Down(InputAction.CallbackContext context);
        void OnShootPlayer2Down(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
    }
    public interface INavigationActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
